name: Upload CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com

      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_READ_PAT }}

      - name: Build projects
        run: npm run build --workspaces || echo "No workspaces found, skipping build";

      - name: Build dist
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync --acl public-read --delete --cache-control max-age=60 ./packages/bitski/dist/bundled/ s3://cdn.bitskistatic.com/js/sdk/v3.3
